# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjJjMDgyNzRkMGE4YjM0ZWQxMzhhZWQ2YTYxZWY4ZGYwNThjMTQ2MGJhYjQ3ODNjNTI2MTU5NThiNTJhYWE0YTJjNWViN2NkNDVlYjhiM2EwODU3ZWUyYzA2ZDNkY2JjNzJjMGJkNTY5YjNhN2JkMzA4NDI4OTgxNzY1YzNiMGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
