# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2ZlYmQ1MzVmZDdkNzZiODNmZGFhNjdlOWM5MDY1OWExOGJlMTMzYjFmNmU3NjZjOWM1OWY0MWRkNDRmMGEyYjgxY2QxOGNhODY0MzhiMzZjZTZhYjAwMjcwYmU3NjllZDE0OWM5Nzc0ZTJmMDNjYTkyYjMwZjM5ZWQzNTc3NTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
